### ISSUE TITLE
Handling of duplicate issues

### ISSUE THREAD

**Issue by adamreisnz** [atom/town-crier#13]
@lee-dohm taking the discussion from https://github.com/atom/atom/issues/14305 here :)

> How would you handle duplicate reports if a bug has already been submitted?

> The same way that we handle them now

I mean when people actually go to the github repo to file a report, they've already located the repo of the package (presumably) and are then instructed to check if an issue has been filed before etc. 

Now that you allow them to select a package with the dropdown, is there an easy way for them to be directed to the correct github repo to actually see if something has been raised before or not? I may have missed this if it is already.

Perhaps a future feature could be to have Town Crier search for other issues with a similar title/keywords and list them to the user as well. But that might be making it _too easy_ for them ;)

**Comment by lee-dohm** [comment]
> Now that you allow them to select a package with the dropdown, is there an easy way for them to be directed to the correct github repo to actually see if something has been raised before or not?

No, there currently isn't a method in the package for this.

I see what you're saying now. I'll think about how this would best be implemented and open a new issue for it. Thanks! :+1:
