### ISSUE TITLE
Categorise / organise packages somehow

### ISSUE THREAD

**Issue by adamreisnz** [atom/town-crier#14]
The list of packages to select from is pretty huge and could be daunting for users. Perhaps if there's a way to split it up into core/userland sections, or even categorize them further somehow to make it easier to find the package you're looking for that'd be great.

Ref https://github.com/atom/atom/issues/14305#issuecomment-313241011

**Comment by lee-dohm** [comment]
Duplicate of https://github.com/atom/town-crier/issues/12
