### ISSUE TITLE
Use "full" text boxes for results

### ISSUE THREAD

**Issue by Arcanemagus** [atom/town-crier#24]
Use the same text box style used in the Description for the Expected and Actual results.

Currently it isn't possible to hit the <kbd>Enter</kbd> key in these text boxes.

**Comment by lee-dohm** [comment]
Ah, ok ... so you want them to be `textarea` elements instead of `input` elements?

**Comment by Arcanemagus** [comment]
That sounds right, I haven't looked at the code to confirm.

**Comment by lee-dohm** [comment]
As discussed in #25, closing this.
