### ISSUE TITLE
Preview shows Expected/Actual content on same line

### ISSUE THREAD

**Issue by Arcanemagus** [atom/town-crier#25]
Related to #24, it seems that the form for this is written assuming the `Expected` and `Actual` content will be a sentence or less, instead of a full description of what was expected and what actually happened.

This means that in the rendered preview the generated Markdown has the responses on the same line:
![image](https://user-images.githubusercontent.com/427137/37537651-7cd9b260-290b-11e8-9320-066d1db6e77e.png)

**Comment by lee-dohm** [comment]
Expected and Actual aren't meant to be big paragraphs, they should be simple statements like what you're showing in the screenshot. But I can understand that might not always be the case.

**Comment by Arcanemagus** [comment]
I tend to use "Actual" to describe what actually happened, for example this is the (fixed) version of the report I was trying to generate here: https://github.com/AtomLinter/linter-pylint/issues/246

**Comment by lee-dohm** [comment]
Yeah, I tend to use the description for that ... otherwise what is that section for?

**Comment by Arcanemagus** [comment]
That... actually makes a lot of sense. I'd be fine with closing this, which means #24 probably also should be closed in order to "guide" users towards that style of filling out the bug.

**Comment by lee-dohm** [comment]
Sounds good :+1: Something to keep in mind for documentation at some point though!
