### ISSUE TITLE
OAuth2 error when submitting report

### ISSUE THREAD

**Issue by Arcanemagus** [atom/town-crier#26]
When attempting to submit a report I get a notification with the following error:
```
Error submitting bug
OAuth2 authentication requires a token or key & secret to be set
```

My own account has 2FA enabled, but as it didn't _ask_ for my account name I'm not sure where this is getting credentials from to attempt to send it in.

It might be a better flow to simply open the user's browser with the issue content's pre-filled for them, like is done [here](https://github.com/AtomLinter/linter-jshint/blob/704ba211dba30a0a5d51cb58914f67457ac9fed5/lib/helpers.js#L230-L243).

**Comment by lee-dohm** [comment]
town-crier reuses the credentials stored by the github package (as stated in the README). So you have to go to the GitHub tab and sign in there first before town-crier will properly submit a bug. Let me know if that isn't working.

> It might be a better flow to simply open the user's browser with the issue content's pre-filled for them,

The problem with opening the user's browser is that there is a limit to how much data can be sent across, a limit that the Unhandled Exception system in Atom runs into from time to time. Even the amount of data that I'm sending now could conceivably butt up against that limit depending on how many packages are installed. And I want to be able to have even more information sent than what it is currently sending.

**Comment by Arcanemagus** [comment]
Looks like this worked just fine after signing into the GitHub tab in the `github` package.

**Comment by lee-dohm** [comment]
Ok cool 😅

**Comment by Arcanemagus** [comment]
Can this error be caught and the user hinted to login there? If I didn't read the README fully enough to catch that you can be _sure_ that somebody getting a bug definitely wouldn't.

**Comment by lee-dohm** [comment]
I thought I had something for that ... but I'll double-check :+1:

**Comment by lee-dohm** [comment]
Ok, it currently doesn't sanity check the creds retrieved. I'll add that.
